modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache-2.0"

[[mods]]
modId = "homecore_debug"
version = "1.1.0"
displayName = "HomeCore Development Device"
authors = "LKDM"
description = '''Development-only HomeCore example device and setup command.'''

[[dependencies.homecore_debug]]
modId = "homecore"
type = "required"
versionRange = "[1.1.0,2.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.homecore_debug]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.250,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homecore_debug]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
