org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
neo_version_range=[21.1.250,21.2)
loader_version_range=[4,)

jei_version=19.57.0.449
jei_version_range=[19.0,)
rei_version=16.0.799
rei_version_range=[16.0,)

mod_id=homecore
mod_name=HomeCore
mod_license=Apache-2.0
mod_version=1.13.0
mod_group_id=fr.lkdm.homecore
mod_authors=LKDM
mod_description=Shared device API and foundation for connected home and base management.
