modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"
[[mods]]
modId="homelink_integration"
version="1.0.0"
displayName="Tests intégration HomeLink"
[[dependencies.homelink_integration]]
modId="homecore"
type="required"
versionRange="[1.10.0,2.0.0)"
ordering="AFTER"
side="BOTH"
